import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Toaster} from "@/components/ui/sonner";
import {AuthProvider} from "@/providers";
import {auth} from "@/auth";
import NavBar from "@/components/nav-bar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'ЭMК - Электроника Медицинская карта',
    description: 'Generated by create next app',
}

const RootLayout = async  ({children}: { children: React.ReactNode }) => {
    const session = await auth()
    return (
        <AuthProvider session={session}>
            <html lang="en">
            <body className={`inter.className min-h-screen`}>
            <header>
                <NavBar/>
            </header>
            <main className="flex min-h-screen flex-col items-center justify-center px-24 bg-gray-50">
                <div className="border-x-[1px] flex justify-center w-full min-h-screen p-4 bg-white">
                    {children}
                </div>
            </main>
            <Toaster/>
            </body>
            </html>
        </AuthProvider>
    )
}
export default RootLayout
